ebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('sellers/', include('sellers.urls')),
    path('', HomeView.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.urls import path
from .views import SellerDashboardView, SellerProfileView, CreateBookView, EditProfileView, BookDeletedView

app_name = 'sellers'

urlpatterns = [
    path('dashboard/', SellerDashboardView.as_view(), name='dashboard'),
    path('profile/', SellerProfileView.as_view(), name='profile'),
    path('create-book/', CreateBookView.as_view(), name='create_book'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('book-delete/<int:book_id>/', BookDeletedView, name='book_delete'),
]

users/urls.py
from django.urls import path
from .views import (CategoryView, LoginView, RegisterView, ProfileView, EditProfileView,
                    DashboardView, LogoutView, ClientSignUpView, BooksDetailView, CartDetailView,
                    UsersListView, SelectRoleView, user_delete)

app_name = 'users'

urlpatterns = [
    path('category/<int:id>/', CategoryView.as_view(), name='category'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('signup/', ClientSignUpView.as_view(), name='signup'),
    path('batafsil/<int:book_id>/', BooksDetailView.as_view(), name='batafsil'),
    path('cart/', CartDetailView.as_view(), name='cart'),

    path('users-list/', UsersListView.as_view(), name='users_list'),
    path('select-role/', SelectRoleView.as_view(), name='select_role'),
    path('user-delete/<int:id>', user_delete, name='user_delete'),


]

sellers/models.py
from django.db import models

sellers/forms.py
from django import forms
from django.forms import widgets
from users.models import Books

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['name', 'author', 'category', 'price', 'quantity', 'description', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

sellers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from users.permissons import SellerRequiredMixin
from .forms import CreateBookForm
from users.models import Books
from users.forms import ProfileEditForm

class SellerDashboardView(SellerRequiredMixin, View):
    def get(self, request):
        return render(request, 'sellers/dashboard.html')

class SellerProfileView(SellerRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile.html')


class CreateBookView(SellerRequiredMixin, View):
    def get(self, request):
        form = CreateBookForm()
        return render(request, 'sellers/create_book.html', {'form': form})

    def post(self, request):
        form = CreateBookForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            author = form.cleaned_data['author']
            category = form.cleaned_data['category']
            price = form.cleaned_data['price']
            quantity = form.cleaned_data['quantity']
            description = form.cleaned_data['description']
            image = form.cleaned_data['image']

            book = Books(
                name=name,
                author=author,
                category=category,
                price=price,
                quantity=quantity,
                description=description,
                image=image
            )
            book.save()

            return redirect('sellers:profile')

        return render(request, 'sellers/create_book.html', {'form': form})


class EditProfileView(SellerRequiredMixin, View):
    def get(self, request):
        form = ProfileEditForm(instance=request.user)
        return render(request, 'sellers/edit_profile.html', {'form': form})

    def post(self, request):
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('sellers:profile')

        form = ProfileEditForm(instance=request.user)
        return render(request, 'sellers/edit_profile.html', {'form': form})



def BookDeletedView(request, book_id):
    book = get_object_or_404(Books, id=book_id)
    book.delete()
    return redirect('/')

sellers/templates/sellers/create_book.html
{% extends 'sellers/dashboard.html' %}

{% block content %}
<div class="container">
    <h1>Add books page</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form}}
        <button type="submit" class="btn btn-outline-info">save</button>
    </form>
</div>
{% endblock %}

sellers/templates/sellers/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}">
  <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css"
  rel="stylesheet"
/>
  <title>Document</title>
</head>
<body>
<!--Main Navigation-->
<header>
  <!-- Sidebar -->
  <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
    <div class="position-sticky">
      <div class="list-group list-group-flush mx-3 mt-4">
        {% if user.user_role == 'admin' %}
        <a
          href="{% url 'users:profile' %}"
          class="list-group-item list-group-item-action py-2 ripple"
          aria-current="true"
        >
        {% else %}
                  <a
          href="{% url 'sellers:profile' %}"
          class="list-group-item list-group-item-action py-2 ripple"
          aria-current="true"
        >
        {% endif %}
            <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>User Profile</span>
            </a>
        {% if user.user_role == 'admin' %}
            <a href="{% url 'users:register' %}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Register</span>
            </a>
        {% else %}
            <a href="{% url 'sellers:create_book' %}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Add book</span>
            </a>
        {% endif %}
        {% if user.user_role == 'admin' %}
            <a href="{% url 'users:users_list' %}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Users list</span>
            </a>
        {% endif %}
      </div>
    </div>
  </nav>
  <!-- Sidebar -->

  <!-- Navbar -->
  <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button data-mdb-button-init
        class="navbar-toggler"
        type="button"
        data-mdb-collapse-init
        data-mdb-target="#sidebarMenu"
        aria-controls="sidebarMenu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Brand -->
      <a class="navbar-brand" href="{% url 'home' %}">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="25"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>

      <!-- Right links -->
      <ul class="navbar-nav ms-auto d-flex flex-row">


        <!-- Avatar -->
        <li class="nav-item dropdown">
          <a
            data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
            href=""
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
              class="rounded-circle"
              height="22"
              alt="Avatar"
              loading="lazy"
            />
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li>
              <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main style="margin-top: 58px;">
  <div class="container pt-4">
    {% block content %}

    {% endblock content %}
  </div>
</main>
<!--Main layout-->
</body>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
></script>
</html>

sellers/templates/sellers/edit_profile.html
{% extends 'sellers/dashboard.html' %}

{% block content %}

<div class="container" >
    <h1>Edit profile page</h1>

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-outline-info">Save</button>
</form>
</div>

{% endblock content %}