ebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('sellers/', include('sellers.urls')),
    path('', HomeView.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.urls import path
from .views import SellerDashboardView, SellerProfileView, CreateBookView, EditProfileView, BookDeletedView

app_name = 'sellers'

urlpatterns = [
    path('dashboard/', SellerDashboardView.as_view(), name='dashboard'),
    path('profile/', SellerProfileView.as_view(), name='profile'),
    path('create-book/', CreateBookView.as_view(), name='create_book'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('book-delete/<int:book_id>/', BookDeletedView, name='book_delete'),
]

users/urls.py
from django.urls import path
from .views import (CategoryView, LoginView, RegisterView, ProfileView, EditProfileView,
                    DashboardView, LogoutView, ClientSignUpView, BooksDetailView, CartDetailView,
                    UsersListView, SelectRoleView, user_delete)

app_name = 'users'

urlpatterns = [
    path('category/<int:id>/', CategoryView.as_view(), name='category'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('signup/', ClientSignUpView.as_view(), name='signup'),
    path('batafsil/<int:book_id>/', BooksDetailView.as_view(), name='batafsil'),
    path('cart/', CartDetailView.as_view(), name='cart'),

    path('users-list/', UsersListView.as_view(), name='users_list'),
    path('select-role/', SelectRoleView.as_view(), name='select_role'),
    path('user-delete/<int:id>', user_delete, name='user_delete'),


]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    USER_ROLE_CHOICES = (
        ('admin', 'admin'),
        ('seller', 'seller'),
        ('client', 'client'),
    )

    image = models.ImageField(upload_to='profile_pics/', blank=True, null=True, default='default.jpg')
    phone_number = models.CharField(max_length=13, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    user_role = models.CharField(max_length=10, choices=USER_ROLE_CHOICES, default='client')

    def save(self, *args, **kwargs):

        if not self.user_role:
            self.user_role = 'client'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username




class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category/', null=True)

    def __str__(self):
        return self.name


class Books(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='books')
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    in_stock = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        return self.price * self.quantity


class Cart(models.Model):
    books = models.OneToOneField(Books, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


    def __str__(self):
        return self.books.name

users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Name"}))
    password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Password"}))


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Username"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))
    password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Password"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput({"class": "form-control", "placeholder": "Confirm Password"}))
    user_role = forms.Select(attrs={'class': "form-control"})

    class Meta:
        model = User
        fields = ('username', 'phone_number', 'first_name', 'last_name', 'password', 'confirm_password', 'user_role')


class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "First Name"}))
    last_name = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Last Name"}))
    phone_number = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Phone Number"}))
    email = forms.CharField(widget=forms.TextInput({"class":"form-control", "placeholder": "Email"}))
    address = forms.CharField(widget=forms.TextInput({"class": "form-control", "placeholder": "Address"}))
    image = forms.ImageField(widget=forms.FileInput({"class": "form-control", "placeholder": "Image"}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'address', 'image']


class ClientRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput({'class': 'form-control'}), required=True)
    phone_number = forms.CharField(widget=forms.TextInput({'class': 'form-control'}), required=False)
    password1 = forms.CharField(widget=forms.PasswordInput({'class': 'form-control'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput({'class': 'form-control'}), required=True)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'phone_number')

    def save(self, commit=True):
        user = super(ClientRegistrationForm, self).save(commit=False)
        user.user_role = 'client'
        user.phone_number = self.cleaned_data['phone_number']
        if commit:
            user.save()
        return user

class SelectRoleForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('user_role',)

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import View
from .models import Books, Category, Cart, User
from .forms import LoginForm, RegisterForm, ProfileEditForm, ClientRegistrationForm, SelectRoleForm
from .permissons import AdminRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

class HomeView(View):
    def get(self, request):
        books = Books.objects.filter(in_stock=True)
        category = Category.objects.all()
        count = Cart.objects.count()
        return render(request, 'users/home.html', {"books": books, 'count':count, "category": category})



class BooksDetailView(View):
    def get(self, request, book_id):
        cart = Cart.objects.all()
        count = Cart.objects.count()
        book = get_object_or_404(Books, id=book_id)
        return render(request, 'users/batafsil.html', {'cart':cart, 'count':count, "book": book})

    def post(self, request, book_id):
        book = get_object_or_404(Books, id=book_id)
        quantity = int(request.POST['cart'])
        if Cart.objects.filter(books=book).exists():
            cart = Cart.objects.filter(books=book).first()
            cart.quantity += quantity
            cart.save()
        else:
            cart = Cart()
            cart.books = book
            cart.quantity = quantity
            cart.save()
        return redirect('/')

class CartDetailView(View):
    def get(self, request):
        count = Cart.objects.count()
        cart = Cart.objects.all()
        return render(request, 'users/cart_detail.html', {'count':count, "cart": cart})


class CategoryView(View):
    def get(self, request, id):
        category = get_object_or_404(Category, id=id)
        books = category.books.all()
        count = Cart.objects.count()
        return render(request, 'users/all_books.html', {'count':count, "books": books})



class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'users/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')

        form = LoginForm()
        return render(request, 'users/login.html', {'form': form})


class RegisterView(AdminRequiredMixin, View):

    def get(self, request):
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            return redirect('users:profile')
        return render(request, 'users/register.html', {'form': form})

class ProfileView(AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile.html')

class EditProfileView(AdminRequiredMixin, View):
    def get(self, request):
        form = ProfileEditForm(instance=request.user)
        return render(request, 'users/edit_profile.html', {'form': form})

    def post(self, request):
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')

        form = ProfileEditForm(instance=request.user)
        return render(request, 'users/edit_profile.html', {'form': form})

class DashboardView(AdminRequiredMixin, View):
    def get(self, request):
        return render(request, 'sellers/dashboard.html')


class ClientSignUpView(View):
    def get(self, request):
        form = ClientRegistrationForm()
        return render(request, 'users/client_signup.html', {'form': form})

    def post(self, request):
        form = ClientRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        return render(request, 'users/client_signup.html', {'form': form})


class UsersListView(View):
    def get(self, request):
        user = User.objects.all()
        return render(request, 'users/users_list.html', {'user': user})

class SelectRoleView(View):
    def get(self, request):
        form = SelectRoleForm()
        return render(request, 'users/select_role.html', {'form': form})

    def post(self, request):
        form = SelectRoleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        return render(request, 'users/select_role', {'form': form})

def user_delete(request, id):
    user = get_object_or_404(User, id=id)
    user.delete()
    return redirect('/')

users/templates/users/all_books.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!--==============================
    Feature Products
    ==============================-->
    <section class="sec-bg3 vs-shop-wrapper   " data-bg-src="{% static 'assets/img/shape/bg-00778.png' %}">
        <div class="section-title text-center">
            <div class="sec-icon"><img src="{% static 'assets/img/icons/sec-icon-2.png' %}" alt="icon"></div>
            <span class="sub-title4">Mahsulotlarimiz</span>
            <h2 class="sec-title3">Eng sara kitoblar</h2>
        </div>
        <div class="container position-relative">
            <div class="filter-menu2 vs-slideTab" data-asnavfor="#shopSlide8440">
                {% for cat in category %}
                <button class="tab-btn active" data-bs-toggle="tooltip" data-bs-placement="left" title="{{cat.name}}">
                    <img src="{% static 'assets/img/shape/filter-icon-bg-1-2.png' %}" alt="image" class="bg-1">
                    <img src="{% static 'assets/img/shape/filter-icon-bg-1-1.png' %}" alt="image" class="bg-2">
                    <i class="flaticon-salad"></i>
                </button>
                {% endfor %}
            </div>

            <div class="vs-carousel" data-slide-show="1" data-lg-slide-show="1" data-md-slide-show="1" data-sm-slide-show="1" data-fade="true" id="shopSlide8440">
                <div id="BestSeller">
                    <div class="row gx-2px justify-content-center">
                        {% for book in books %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="vs-product-box3 ">
                                <div class="product-img">
                                    <a href=""><img src="{{book.image.url}}" alt="Product Image" class="w-100"></a>
                                    <span class="product-tag2">New</span><span class="product-tag3">Book</span>
                                </div>
                                <div class="actions-btn">
                                    <a href="{{ book.images.url }}" class="icon-btn popup-image"><i class="far fa-search"></i></a>
                                    <a href="wishlist.html" class="icon-btn"><i class="fal fa-heart"></i></a>
                                    <a href="{% url 'users:batafsil' book.id %}" class="vs-btn style4 cart-btn">Batafsil</a>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating-box">5.0<div class="star-rating" role="img" aria-label="Rated 5.00 out of 5"><span style="width:100%">Rated <strong class="rating">5.00</strong> out of 5</span></div>
                                    </div>
                                    <h4 class="product-title"><a href="shop-details.html">{{book.name}}</a></h4>
                                    <span class="price"><strong>${{book.price}}</strong></span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

users/templates/users/batafsil.html
{% extends 'base.html' %}

{% block content %}
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{book.image.url}}" alt="..." /></div>
                    <div class="col-md-6">
                        <div class="small mb-1"><b>Fazogir Books</b> mahsulotlari</div>
                        <h1 class="display-5 fw-bolder">{{book.name}}</h1>
                        <div class="fs-5 mb-5">
                            <span>${{book.price}}</span>
                        </div>
                        <p class="lead">{{book.description}}</p>
                        <div class="d-flex">
                            <form action="" method="post">
                                {% csrf_token %}
                                <input class="form-control text-center me-3" id="inputQuantity" name="cart" type="num" value="1" style="max-width: 3rem" />
                                <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                                <i class="bi-cart-fill me-1"></i>
                                Add to cart
                            </button>
                            </form>
                        </div>
                        <br>
                            {% if user.user_role == 'seller' %}
                            <a href="{% url 'sellers:book_delete' book.id %}" class="btn btn-outline-danger">
                                <i class="fa-solid fa-trash-can"></i> Delete
                            </a>
                            {% endif %}
                        <div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock content %}

users/templates/users/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!--==============================
    Feature Products
    ==============================-->
    <section class="sec-bg3 vs-shop-wrapper   " data-bg-src="{% static 'assets/img/shape/bg-00778.png' %}">
        <div class="section-title text-center">
            <div class="sec-icon"><img src="{% static 'assets/img/icons/sec-icon-2.png' %}" alt="icon"></div>
            <span class="sub-title4">Savat</span>
            <h2 class="sec-title3">Buyurtmalaringiz</h2>
        </div>
        <div class="container position-relative">
            <div class="filter-menu2 vs-slideTab" data-asnavfor="#shopSlide8440">
                <button class="tab-btn active" data-bs-toggle="tooltip" data-bs-placement="left" title="{{cat.name}}">
                    <img src="{% static 'assets/img/shape/filter-icon-bg-1-2.png' %}" alt="image" class="bg-1">
                    <img src="{% static 'assets/img/shape/filter-icon-bg-1-1.png' %}" alt="image" class="bg-2">
                    <i class="flaticon-salad"></i>
                </button>
            </div>

            <div class="vs-carousel" data-slide-show="1" data-lg-slide-show="1" data-md-slide-show="1" data-sm-slide-show="1" data-fade="true" id="shopSlide8440">
                <div id="BestSeller">
                    <div class="row gx-2px justify-content-center">
                    {% for cart in cart %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="vs-product-box3 ">
                                <div class="product-img">
                                    <a href=""><img src="{{cart.books.image.url}}" alt="Product Image" class="w-100"></a>
                                    <span class="product-tag2">New</span><span class="product-tag3">Book</span>
                                </div>
                                <div class="actions-btn">
                                    <a href="{{ cart.books.images.url }}" class="icon-btn popup-image"><i class="far fa-search"></i></a>
                                    <a href="wishlist.html" class="icon-btn"><i class="fal fa-heart"></i></a>
                                    <a href="" class="vs-btn style4 cart-btn">Delete</a>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating-box">5.0<div class="star-rating" role="img" aria-label="Rated 5.00 out of 5"><span style="width:100%">Rated <strong class="rating">5.00</strong> out of 5</span></div>
                                    </div>
                                    <h4 class="product-title"><a href="shop-details.html">{{cart.books.name}}</a></h4>
                                    <span class="price"><strong>${{cart.books.price}}</strong></span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

users/templates/users/client_signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Register Page</h1>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-info" type="submit">Register</button>
    </form>
</div>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'sellers/dashboard.html' %}

{% block content %}

<div class="container" >
    <h1>Edit profile page</h1>

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-outline-info">Save</button>
</form>
</div>

{% endblock content %}

users/templates/users/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!--==============================
        Blog Area
    ==============================-->
    <section class="vs-blog-wrapper space-top space-md-bottom" id="blog">
        <div class="container">

            <div class="row ">
                {% for cat in category %}
                <div class="col-sm-6 col-lg-4">
                    <div class="vs-blog blog-grid">
                        <div class="blog-img image-scale-hover">
                            <a href="{% url 'users:category' cat.id %}"><img src="{{cat.image.url}}" alt="Blog Image" class="w-100"></a>
                        </div>
                        <div class="blog-content">
                            <h4 class="blog-title fw-semibold"><a href="{% url 'users:category' cat.id %}"><b></b><h3>{{cat.name}}</h3><b></b></a></h4>
                            <div class="blog-meta">
                                <h5>January 04, 2022</h5>
                                <h5>500 Views</h5>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
        <!--==============================
    Feature Products
    ==============================-->
    <section class=" vs-shop-wrapper  space-top">
        <div class="section-title text-center">
            <div class="sec-icon"><img src="{% static 'assets/img/icons/sec-icon-2.png' %}" alt="icon"></div>
            <span class="sub-title4">Aksiyalar</span>
            <h2 class="sec-title3">Abu-Hay-Books chegirmalar</h2>
        </div>
        <div class="container">
            <div class="row vs-carousel dots-style2" data-slide-show="2" data-lg-slide-show="2" data-sm-slide-show="1" data-dots="true">
                {% for book in books %}
                <div class="col-xl-6">
                    <div class="vs-product-box6">
                        <div class="product-shape"><img src="{% static 'assets/img/shape/shop-shape-10-1.png' %}" alt="Shape image"></div>
                        <div class="product-img">
                            <a href="shop-details.html"><img src="{{book.image.url}}" alt="Product Image" class="w-100"></a>
                        </div>
                        <div class="product-content">
                            <div class="product-rating-box">5.0<div class="star-rating" role="img" aria-label="Rated 5.00 out of 5"><span style="width:100%">Rated <strong class="rating">5.00</strong> out of 5</span></div>
                            </div>
                            <h4 class="product-title"><a href="shop-details.html">{{ book.name }}</a></h4>
                            <span class="price"><strong>${{book.price}}</strong></span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Login Page</h1>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-info" type="submit">Log in</button>
    </form>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'sellers/dashboard.html' %}

{% block content %}
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-body-tertiary rounded-3 p-3 mb-4">
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="{{user.image.url}}" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3">{{user.first_name}} {{user.last_name}}</h5>
            <p class="text-muted mb-1">{{user.phone_number}}</p>
            <p class="text-muted mb-4">{{user.address}}</p>
            <div class="d-flex justify-content-center mb-2">
              <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary">Follow</button>
              {% if user.user_role == 'admin' %}
              <a href="{% url 'users:edit_profile' %}" class="btn btn-outline-primary ms-1">Edit</a>
              {% else %}
              <a href="{% url 'sellers:edit_profile' %}" class="btn btn-outline-primary ms-1">Edit</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{user.email}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{user.phone_number}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Mobile</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{user.phone_number}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{user.address}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

users/templates/users/register.html
{% extends 'sellers/dashboard.html' %}

{% block content %}
<div class="container">
    <h1>Register Page</h1>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-outline-info" type="submit">Register</button>
    </form>
</div>
{% endblock content %}

users/templates/users/select_role.html
{% extends 'sellers/dashboard.html' %}

{% block content %}
<html>
<head>
    <title>Select Role</title>
</head>
<body>
    <h1>Select Your Role</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>
{% endblock content %}

users/templates/users/users_list.html
{% extends 'sellers/dashboard.html' %}


{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Username</th>
      <th scope="col">Full name</th>
      <th scope="col">Phone number</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
  {% for users in user %}
  <tr>
      <th scope="row">{{users.id}}</th>
      <td>{{users.username}}</td>
      <td>{{users.first_name}} {{users.last_name}}</td>
      <td>{{users.phone_number}}</td>
      <td><a href="{% url 'users:select_role' %}" class="btn btn-outline-info">Edit</a>
      <a href="{% url 'users:user_delete' users.id %}" class="btn btn-outline-danger">Delate</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}
<!--aka views.py da yana : qoyib kettingiz / ni orniga-->